
env:
   global:
     - CONAN_ARCHS: "x86_64"
     - CONAN_REFERENCE: "aws-sdk-cpp/1.7.212"
     - CONAN_USERNAME: "kmaragon"
     - CONAN_LOGIN_USERNAME: "kmaragon"
     - CONAN_CHANNEL: "stable"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/kmaragon/conan"
     - CONAN_STABLE_BRANCH_PATTERN: "release/*"
     - CONAN_UPLOAD_ONLY_WHEN_STABLE: 1

linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:

      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7

      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=lasote/conangcc8

      - <<: *linux 
        env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=lasote/conanclang60

      - <<: *osx
        osx_image: xcode9
        env: CONAN_APPLE_CLANG_VERSIONS=9.0

      - <<: *osx
        osx_image: xcode9.3
        env: CONAN_APPLE_CLANG_VERSIONS=9.1

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
